apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmtest 
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: helloworld
    helm:
      releaseName: hellorel001
    repoURL: https://jiwenke.github.io/helmsrc
    targetRevision: 15.6.0
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
